[package]
name = "simpserv"
version = "0.1.0"
authors = ["grayarea11235 <ciaran.dunn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
